name: Main

on: issue_comment

jobs:
  main:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo A comment on PR $NUMBER
        env:
          OBJ: ${{ github.event.issue }}
          NUMBER: ${{ github.event.issue.number }}
